export default {
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  UPDATE_CURRENT_PRICE: 'UPDATE_CURRENT_PRICE',
  UPDATE_CHOSEN_INGREDIENTS: 'UPDATE_CHOSEN_INGREDIENTS',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  RESET_INGREDIENTS: 'RESET_INGREDIENTS',
  ADD_TO_BASKET: 'ADD_TO_BASKET'
}
