export default {
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  UPDATE_CURRENT_PRICE: 'UPDATE_CURRENT_PRICE',
  UPDATE_CHOSEN_INGREDIENTS: 'UPDATE_CHOSEN_INGREDIENTS',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  RESET_INGREDIENTS: 'RESET_INGREDIENTS',
  ADD_TO_BASKET: 'ADD_TO_BASKET',
  CONFIRM_ORDER: 'CONFIRM_ORDER',
  PUT_INGS_TO_GLOBAL_STATE: 'PUT_INGS_TO_GLOBAL_STATE',
  PUT_ID_TO_GLOBAL_STATE: 'PUT_ID_TO_GLOBAL_STATE',
  PUT_CART_TO_GLOBAL_STATE: 'PUT_CART_TO_GLOBAL_STATE',
  INITIAL_ING_LOAD: 'INITIAL_ING_LOAD',
  ADD_EXTRA_INGREDIENT: 'ADD_EXTRA_INGREDIENT',
  SEND_BURGER_TO_DB: 'SEND_BURGER_TO_DB',
  PUT_TOTAL_PRICE_TO_GS: 'PUT_TOTAL_PRICE_TO_GS',
  START_CART_LOAD: 'START_CART_LOAD',
  START_SENDING_ORDER: 'START_SENDING_ORDER',
  SHOW_SUCCESS_MESSAGE: 'SHOW_SUCCESS_MESSAGE'
}
